name: Build pipeline
trigger:
- main

stages:

- stage: build
  displayName: Build
  jobs: 

  - template: .azure-pipeline-templates/dotnet-build.yml

  - template: .azure-pipeline-templates/dotnet-build.yml
    parameters:
      sdk: '3.1'
      framework: 'netcoreapp3.1'

- stage: test
  displayName: Test
  jobs: 

  - template: .azure-pipeline-templates/dotnet-test.yml

  - template: .azure-pipeline-templates/dotnet-test.yml
    parameters:
      sdk: '3.1'
      framework: 'netcoreapp3.1'
