parameters:
- name: sdk
  type: string
  default: '6.0'
- name: framework
  type: string
  default: 'net6.0'
- name: configuration
  type: string
  default: 'Release'
- name: project
  type: string
  default: '.'
  
jobs: 
- job: dotnet_test_${{ replace(parameters['framework'], '.', '_') }}
  pool:
    vmImage: ubuntu-latest
  displayName: Test ${{ parameters.framework }}
  steps:
  - template: .dotnet-restore.yml
  - task: UseDotNet@2
    inputs:
      version: ${{ parameters.sdk }}.x
      #performMultiLevelLookup: true
      includePreviewVersions: true
  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: 'Tests/Tests.csproj'
      packagesDirectory: packages
      arguments: '--configuration ${{ parameters.configuration }} --framework ${{ parameters.framework }} --no-restore --test-adapter-path:. --logger:"nunit;LogFilePath=test-result.xml'
    continueOnError: 'true'
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: NUnit
      testResultsFiles: '**/test-result.xml'
      failTaskOnFailedTests: true