parameters:
- name: sdk
  type: string
  default: '5.0'
- name: framework
  type: string
  default: 'net5.0'
- name: configuration
  type: string
  default: 'Release'
- name: project
  type: string
  default: '.'
  
jobs: 
- job: dotnet_test_${{ replace(parameters['sdk'], '.', '_') }}
  pool:
    vmImage: ubuntu-latest
  displayName: Test .NET ${{ parameters.sdk }}
  container: mcr.microsoft.com/dotnet/sdk:${{ parameters.sdk }}
  steps:
  - script: |
      dotnet restore ${{ parameters.project }} \
      --locked-mode
  - script: |
      dotnet test ${{ parameters.project }} \
      --configuration ${{ parameters.configuration }} \
      --framework ${{ parameters.framework }} \
      --no-restore \
      --test-adapter-path:. \
      --logger:"nunit;LogFilePath=test-result.xml"
    continueOnError: 'true'
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: NUnit
      testResultsFiles: '**/test-result.xml'
      failTaskOnFailedTests: true